/**:
  ros__parameters:
    ISR_M2:
      size: 0.70
      wheels:
        separation: 0.5
        radius: 0.32
      linear:
        velocity: 1.00
        acceleration: 0.60
      angular:
        velocity: 0.50
        acceleration: 0.30